# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/taher/github/sdf-font/lib/msdfgen/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/taher/github/sdf-font/lib/msdfgen/cmake/msdfgenConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindFreetype.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/SelectLibraryConfigurations.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.22.2/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/taher/github/sdf-font/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -H/Users/taher/github/sdf-font -B/Users/taher/github/sdf-font
